class OrganizationsController < ApplicationController
  before_action { @organization = Organization.find_by(id: params[:id]) }

  def index
    @organizations = Organization.all
  end

  def show
  end

  def new
    @organization = Organization.new
  end

  def create
    Organization.create!(
      name:         params[:organization][:name],
      contact_name: params[:organization][:contact_name],
      contact_mail: params[:organization][:contact_mail]
    )
    redirect_to organizations_path
  end

  def edit
  end

  def update
    Organization.update(
      params[:id],
      params.require(:organization)
      .permit(:name, :contact_name, :contact_mail)
    )
    redirect_to organizations_path
  end

  def destroy
    Organization.delete params[:id]
    redirect_to organizations_path
  end

  def contact
  end

  def deliver
    # Run `bundle exec mailcatcher` if you're trying to test this.
    #
    # Mail is viewable at http://localhost:1080
    #
    # The destination address is deliberately incorrect here to prevent
    # accidental delivery to a real email address generated by Faker.
    body = "Actual destination:
            #{@organization.contact_mail}\n\n#{params[:body]}"

    Mail.deliver(to: 'test@example.com',
                 from: 'noreply@aaf.edu.au',
                 subject: params[:subject],
                 body: body,
                 content_type: 'text/html; charset=UTF-8')

    redirect_to organization_path(@organization)
  end
end
